分组聚合

In [1]:
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd

In [5]:
df = pd.read_csv('employees.csv')
# 去掉 department_id 列中的空值行
df = df.dropna(subset=['department_id'])

# 把该列转成整数类型
df['department_id'] = df['department_id'].astype('int64')

# 计算不同部门的平均薪资
df.groupby('department_id')['salary'].mean()

# （可选）查看分组信息
df.groupby('department_id').groups        # 返回 {组名: 对应行索引列表}
df.groupby('department_id').get_group(20) # 取出 department_id == 20 的那一组数据
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [6]:
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110